### ISSUE TITLE
I can´t run downloader on Windows 10

### ISSUE THREAD

**Issue by ebv25** [AZn5ReD/saplearninghub-pdf-downloader-gui#14]
Greetings AZn5ReD,
I would like you to help me understand: Where do I have to edit the parameters described in the prerequisites ?, and What should I do in the part of the statement that says "The path of the downloader script (build result of ..."?
Tried it on Windows 10 but got no results.
My link is:
https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/ebook/ADM100_EN_Col21/index.html

I thank you in advance.

**Comment by AZn5ReD** [comment]
You need to download the latest release, extract it and start the "qode.exe".
Then the window will appear :
![image](https://user-images.githubusercontent.com/1781837/102016899-a8eb9480-3d63-11eb-99b7-9f5476571895.png)

**Comment by ebv25** [comment]
Great job!
The PDF downloader works correctly.
I am very grateful.

**Comment by XKT85** [comment]
I'm sorry  but what do you mean with "qode.exe". I can' t find these exe.

**Comment by XKT85** [comment]
I put the information in this dialog but nothing happens. The programm close if i put the button download.
