### ISSUE TITLE
ENV error

### ISSUE THREAD

**Issue by pp7y** [AZn5ReD/saplearninghub-pdf-downloader-gui#7]
Hi I'm kinda new here sry if I'm having a rookie issue here, but as I tired to run the config file I gotten an ENV error.
Here's the snippet from the log:
10 silly lifecycle saplearninghub-pdf-downloader@1.0.0~start: Args: [ '/d /s /c', 'env NODE_ENV=production node ./dist/index.js' ]
11 silly lifecycle saplearninghub-pdf-downloader@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle saplearninghub-pdf-downloader@1.0.0~start: Failed to exec start script
13 verbose stack Error: saplearninghub-pdf-downloader@1.0.0 start: `env NODE_ENV=production node ./dist/index.js`
13 verbose stack Exit status 1
Do you have an idea what the issue might be?
Thank you and cheers,

**Comment by AZn5ReD** [comment]
Hi,

Have you tried to use the absolute path (starting with "/") to refer to the "index.js" ?
If it's still not working, could you please send a capture of the program ?
Finally, if you're in a hurry, you can still use the "CLI" version of the program: https://github.com/AZn5ReD/saplearninghub-pdf-downloader. It's less buggy :)

**Comment by AZn5ReD** [comment]
Should be fixed with the new release
